In [7]:
import argparse

import numpy as np

import config
import models
import retrieval
import utils
from utils import StatusCode

In [16]:
matrix = sp.load_npz("./data/sparseTransition.npz")

In [18]:
matrix.sum(axis=1).sum()

11021

In [19]:
matrix = sp.load_npz("./data/sparseTransition.npz")
matrix.sum(axis=1).sum()

11021

In [20]:
matrix = sp.load_npz("./data/sparseTransition.npz")
matrix.sum(axis=1).sum()

11021

In [1]:
import numpy as np

In [2]:
x = np.arange(10)
np.random.shuffle(x)

In [3]:
x

array([2, 1, 6, 8, 5, 7, 0, 9, 4, 3])

In [6]:
np.argsort(np.argsort(-x))

array([7, 8, 3, 1, 4, 2, 9, 0, 5, 6])

In [5]:
np.argsort(x)

array([6, 1, 0, 9, 8, 4, 2, 5, 3, 7])

In [2]:
data = np.loadtxt("output/GPR-CS.outputs.txt", dtype=object)

In [3]:
data[0]

array(['14-1', 'Q0', '66049', '1', '328.5', 'GPR-CS'], dtype=object)

In [4]:
data[-1]

array(['12-1', 'Q0', '10789', '17885', '4.5', 'GPR-CS'], dtype=object)

In [6]:
rev_data = np.flip(data, axis=0)